name: dartnow
description: Dart Now command line interface
version: 0.1.8
author: Kasper Peulen <kasperpeulen@gmail.com>
homepage: https://github.com/dartnow/dartnow_cli
environment:
  sdk: '>=1.11.0 <2.0.0'
executables:
  dartnow:
  dartnow_admin:
dependencies:
  path: '^1.3.6'
  args: '^0.13.2'
  yaml: '^2.1.3'
  prompt: '^0.1.7'
  github:
    git:
      url: https://github.com/kasperpeulen/github.dart.git
      ref: editGist2
  analyzer: any
  test: '^0.12.3+8'
  http: '^0.11.3'
